name: Clean, Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  commit-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
#      - name: Setup Testcontainers Cloud Client
#        uses: atomicjar/testcontainers-cloud-setup-action@v1
#        with:
#          token: ${{ secrets.TC_CLOUD_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests with Testcontainers
        run: ./gradlew clean build -x test -PskipSigning=true --stacktrace

